# https://taskfile.dev

version: '3'
dotenv: ['.env']
vars:
  API_TOKEN:
    sh: curl -s -X POST http://localhost:8134/api/user/login -d '{"userName":"test1", "password":"test"}' | jq -r .access_token

tasks:
  user-create:
    cmds:
      - curl -X POST http://localhost:8134/api/user/signup -d '{"firstName":"George", "lastName":"Washington", "userName":"test1", "password":"test", "email":"user2@gmail.com", "phone":"800-555-1235"}'
  
  user-login:
    cmds:
      - curl -X POST http://localhost:8134/api/user/login -d '{"userName":"test1", "password":"test"}'

  user-get:
    cmds:
      - "curl -H 'Authorization: Bearer {{ .API_TOKEN }}' -X GET http://localhost:8134/api/user/2"

  psql:
    cmds:
      - echo $PSQL_HOST
      - psql 'postgresql://{{ .PSQL_USER }}:{{ .PSQL_PASS }}@{{ .PSQL_HOST }}:5432/fooddelivery'

  robot:
    dir: '{{.TASKFILE_DIR}}/robot'
    cmds:
      - robot --outputdir ../results . 