# https://taskfile.dev

version: '3'
dotenv: ['.env']
tasks:
  user-create:
    cmds:
      - curl -X POST http://localhost:8134/api/user/signup -d '{"firstName":"George", "lastName":"Washington", "userName":"test1", "password":"test", "email":"user1@gmail.com", "phone":"800-555-1234"}'
  
  user-login:
    cmds:
      - curl -X POST http://localhost:8134/api/user/login -d '{"userName":"test1", "password":"test"}'

  user-get:
    cmds:
      - "curl -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwidXNlcl9uYW1lIjoidGVzdDEiLCJleHAiOjE3NzUwNDE3NTZ9.mGU-_DRyRrNaw7smm_k2pnpRa4CBpy_4g3Q6oRUYZw0' -X GET http://localhost:8134/api/user/1"

  psql:
    cmds:
      - echo $PSQL_HOST
      - psql 'postgresql://{{ .PSQL_USER }}:{{ .PSQL_PASS }}@{{ .PSQL_HOST }}:5432/fooddelivery'

  robot:
    dir: '{{.TASKFILE_DIR}}/robot'
    cmds:
      - robot --removekeywords "NAME:Add AWS Secrets" --outputdir ../results . 